inherit_from: .rubocop_todo.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: true
Layout/LineLength:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - 'test/**/*'
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
